### ISSUE TITLE
No screenshots

### ISSUE THREAD

**Issue by sfantu** [qtile/qtile-examples#35]
I mean shouldn't examples have screenshots? How are people suppose to know how nice something looks if they can't see it.

**Comment by tych0** [comment]
On Fri, Jan 26, 2018 at 03:20:04PM +0000, Valentin wrote:
> I mean shouldn't examples have screenshots? How are people suppose to know how nice something looks if they can't see it.

Perhaps, but screenshots won't show hotkeys and other interesting code
and configuration ideas, which IMO is 99% of the value of this repo.

See the screenshots here: http://www.qtile.org/screenshots/

They just aren't that cool looking :)

**Comment by zordsdavini** [comment]
I think all screenshots depends on creator. If creator wants to make you config more attractive - he could add some. I think this can be closed

**Comment by ramnes** [comment]
Well I do agree with OP that a huge part of a config is just about the rice. Not sure what we could do, though. I'll close this for now, if anyone has a great idea on what we could do, please comment here and I'll re-open if it's doable.
