### ISSUE TITLE
Missing scripts

### ISSUE THREAD

**Issue by Selion05** [qtile/qtile-examples#46]
https://github.com/qtile/qtile-examples/blob/f147c2271827f18a9b459b356bfb4df265982921/zordsdavini/bin/setup_screens#L16

I'm curious what's in those `${SCREENS_COUNT}screens.sh` scripts. @zordsdavini  Would you mind sharing them? 

Either way I'm looking for way to setup qtile based on attached monitors. Most multiscreen setups depends on the hostname which doesn't work for me.  Did I miss that in the docs?

**Comment by zordsdavini** [comment]
yea, sure :) This is simple setup. You create your setup with xrandr (I did by arandr) and save it under `1screens.sh` or `2screens.sh` for one or two monitors. The sript will call one of them. 
Today I don't use it any more. `autorandr -c` I use. 
https://wiki.archlinux.org/index.php/Xrandr#Automatically_switch_configurations_with_autorandr

and today qtile config 
https://github.com/zordsdavini/dotfiles/blob/master/.config/qtile/config.py

**Comment by Selion05** [comment]
nice thanks for sharing your new config! Now I know how to do it :)

As far as I understand your new config doesn't depend on the number of monitors anymore. right? 

 Thanks!

**Comment by zordsdavini** [comment]
yes. This is one time fix: plug all monitors, adjust by `arandr`, save with `autorandr` and call it on monitor change.

**Comment by zordsdavini** [comment]
this can be closed
