### ISSUE TITLE
Where are the xinitrc examples ?

### ISSUE THREAD

**Issue by Wrexes** [qtile/qtile-examples#53]
Hello,
While trying to configure Qtile for my first use of it, I found that the documentation recommends [running it in a secondary X session](http://docs.qtile.org/en/latest/manual/hacking.html#second-x-session) in order to test it.

When using the provided script ( `qtile/scripts/xephyr`), I get this error :
![image](https://user-images.githubusercontent.com/5567164/105181775-86038b80-5b2c-11eb-925b-8f1db5d8ff1e.png)
Kinda weird.

So I thought maybe I should try using `startx`.
Further reading the documentation, I've been led to this repository by a link saying it would contain examples of xinitrc files fitting my needs... but it doesn't ?

I never used `startx` before, only login managers.
And this is my first time using qtile so I don't know what  sequence of action is recommended to start it from console/script.

Any help would be appreciated.
Thanks.

**Comment by ramnes** [comment]
Try `startx qtile start`.

**Comment by Wrexes** [comment]
Oh. Simply feeding it commands is enough ? That's interesting.
In the end I've been looking at the basic `/etc/X11/xinit/xinitrc` and slapped a few commands at the bottom plus `qtile -l DEBUG -c ~/path/to/config/to/test.py`, saved that edited copyas `~/.xinitrc` and it works fine hen using `startx` in a TTY.
And thanks for the tip !
