### ISSUE TITLE
Systems with Dual - Triple batteries

### ISSUE THREAD

**Issue by Sniki** [qtile/qtile-examples#55]
Hi,

Is there a way to merge the percentage of two or three batteries and report as one into the battery widget ?

I have 5 Lenovo ThinkPad laptops and most of them have two batteries (internal + standard removable battery).

I have two battery widgets in the bar (one for BAT0 & and one for BAT1), that takes additional space into the bar and is kind of counter intuitive.
It would be great to have a feature/option/widget to report % for all available batteries into one icon/widget/percentage.

That would free up space for another widget (especially for laptops) and report as it should be (like Desktop Environments do, their menu bar battery percentage icon shows total percentage on how much battery you have from all of the batteries).

Current implementation:

Screenshot: [Link](https://raw.githubusercontent.com/Sniki/Dotfiles/master/.config/qtile/Screenshot.png) 
Config: [Link](https://github.com/Sniki/Dotfiles/blob/master/.config/qtile/config.py)

**Comment by ramnes** [comment]
Hi @sniki,

Sorry for the late answer, but we're not really watching issues here! You'd have more luck as a discussion on the main repository: https://github.com/qtile/qtile/discussions :)
