### ISSUE TITLE
autostart.sh not working

### ISSUE THREAD

**Issue by jayjamesdr** [qtile/qtile-examples#56]
https://ibb.co/jVbJWT3
https://ibb.co/wsjgnq2

ı'm not python programmer ı don't understand why not working
http://docs.qtile.org/en/latest/manual/config/hooks.html?highlight=autostart.sh#autostart
ı try read this page my english not good

**Comment by ramnes** [comment]
`chmod a+x ~/.config/qtile/autostart.sh`?
