### ISSUE TITLE
The up volume and down buttons dont work, like the brightness button

### ISSUE THREAD

**Issue by Borisd93** [qtile/qtile-examples#57]
This more than a issue, maybe be an pull request but i cannot up or down my vol or brightness, with the buttons.

I have QTile 0.18, i updated 3 hours ago

**Comment by ramnes** [comment]
You'd have more luck as a discussion on the main repository: https://github.com/qtile/qtile/discussions :)

But you probably want to give more details anyway, i.e. what you tried, what you're seeing, and what you'd expect to see.

**Comment by Borisd93** [comment]
Well i dont see anything when i touch volume/brightness UP or Down

**Comment by ramnes** [comment]
Qtile is not responsible for such things, ACPI is. 😉
