### ISSUE TITLE
time logger do not work 

### ISSUE THREAD

**Issue by mosaleh52** [qtile/qtile-examples#68]
I have tried to use timelogger.py in @oboingo but nothing happen 
I have made the log txt file in same location fixed missing . before config and imported the file to my config and still nothing happen

**Comment by m-col** [comment]
Do you get any output into the regular qtile log?  Check that the folder to that times log file exists

**Comment by mosaleh52** [comment]
It worked after restarting, i searched in log for the reason but there is nothing i can notice 
thanks @m-col
